export const CHANGE_LIST = 'CHANGE_LIST';
export const ADD_LIST_ITEM = 'ADD_LIST_ITEM';
export const CHANGE_DISPLAY = 'CHANGE_DISPLAY';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const CHANGE_LIST_ITEM = 'CHANGE_LIST_ITEM';
export const CHANGE_FUTURE = 'CHANGE_FUTURE';
export const CHANGE_PAST = 'CHANGE_PAST';
export const CHANGE_ALL = 'CHANGE_ALL';
